### ISSUE TITLE
Using language picker in footer breaks document layout

### ISSUE THREAD

**Issue by mrfatguy** [lajax/yii2-language-picker#12]
Similar to #10. When _yii2-language-picker_ is placed in footer or anywhere near the bottom border of page, it renders like this:

![yii-l-p-1](https://cloud.githubusercontent.com/assets/2903392/7020302/3145efb8-dd18-11e4-8518-006447339759.png)

Notice, that the very same footer, without language picker renders correctly like this:

![yii-l-p-2](https://cloud.githubusercontent.com/assets/2903392/7020303/34df3eae-dd18-11e4-93a2-08864c6bc746.png)

In my opinion, this could happen, because for drawing dropdown you're probably using hidden, but not positioned absolutely divs. If they have anything else than `postion: absolute` in their styles, they will "infect" document layout and possibly break it.

**Comment by trejder** [comment]
Thank you so much for this fix. However, I have a technical question, since I am a newbie to Composer.

I have installed your extension into my application, [using Composer](https://github.com/lajax/yii2-language-picker#installation). Yesterday I got notification, that you updated it. Today morning, I have executed `php composer.phar update` followed by `php composer.phar install` and in both cases Composer claims: `Nothing to install or update`.

What am I missing? How should I update your extension in my application, whenever you push some changes to this repository? Thank you for your time spent on answering this.

**Comment by trejder** [comment]
It seems, that everything is OK. You have comitted your changes yesterday and two days ago, but since you haven't created a new release, then Composer correctly claims, that there is nothing to update (if I get these things right). Therefore, I must wait for your new release or update the code manually, by fetching newest version out of this repository.
